### ISSUE TITLE
error: failed to run custom build command for `alsa-sys v0.1.2`

### ISSUE THREAD

**Issue by sornas** [default-username-852/schack-gui#1]
https://pastebin.com/QMmpypg5

**Comment by sornas** [comment]
`error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/gustav/git/schack-gui/target/debug/build/libudev-sys-b835e4b8fc73e9f2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"`: No such file or directory (os error 2)"', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x7f37e885cb5b - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x7f37e885cb5b - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x7f37e885cb5b - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x7f37e885cb5b - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x7f37e885cb5b - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x7f37e885c837 - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:214
   6:     0x7f37e885d220 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:477
   7:     0x7f37e885cda2 - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                               at src/libstd/panicking.rs:384
   8:     0x7f37e885cc86 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x7f37e88762ed - core::panicking::panic_fmt::h2daf88b2616ca2b2
                               at src/libcore/panicking.rs:85
  10:     0x7f37e880dfe7 - core::result::unwrap_failed::he1b552268d11391f
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11:     0x7f37e880e1a8 - core::result::Result<T,E>::unwrap::h0cfd7c68b9d03ea3
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:800
  12:     0x7f37e880c646 - build_script_build::main::hb127649be56a5314
                               at /home/gustav/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38
  13:     0x7f37e880db00 - std::rt::lang_start::{{closure}}::h4fb687340e8b2e2c
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  14:     0x7f37e885cc73 - std::rt::lang_start_internal::{{closure}}::h447d8812e3ee306d
                               at src/libstd/rt.rs:49
  15:     0x7f37e885cc73 - std::panicking::try::do_call::h4a61cb372364c745
                               at src/libstd/panicking.rs:296
  16:     0x7f37e88631ba - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  17:     0x7f37e885d72d - std::panicking::try::hdf71f938885bca42
                               at src/libstd/panicking.rs:275
  18:     0x7f37e885d72d - std::panic::catch_unwind::h7e85dbf162b1611a
                               at src/libstd/panic.rs:394
  19:     0x7f37e885d72d - std::rt::lang_start_internal::h1e06cc26b9fc25ea
                               at src/libstd/rt.rs:48
  20:     0x7f37e880dad9 - std::rt::lang_start::he32e1f98a843b4b5
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  21:     0x7f37e880c75a - main
  22:     0x7f37e7800f8a - __libc_start_main
  23:     0x7f37e880bdca - _start
  24:                0x0 - <unknown>`

**Comment by violaso** [comment]
I had your issue at home for a while. If I remember correctly, I tried to compile Rust using Ubuntu. As soon as I gave up and installed Rust for Windows, it fixed itself. But in-case you're not on a Windows machine (give up if you're on a Mac):

### Linux

According to [this thread](https://gitlab.com/susurrus/serialport-rs/issues/46):
> For GNU Linux `pkg-config` and `libudev` headers are required (`pkg-config` and `libudev-dev` on Ubuntu respectively).

### General Libudev requirements

According to the [lib's documentation](https://github.com/dcuddeback/libudev-sys): 
> In order to use the libudev-sys crate, you must have a Linux system with the libudev library installed *[...]*.

> [O]ne must define the environment variables PKG_CONFIG_DIR, PKG_CONFIG_LIBDIR, and PKG_CONFIG_SYSROOT_DIR for the default pkg-config. It's also necessary to set PKG_CONFIG_ALLOW_CROSS to tell Rust's pkg-config helper that it's okay to proceed with a cross-compile.

**Comment by sornas** [comment]
As it happens, this is with Windows 10 and Windows Subsystem for Linux. I'll try to google a bit when I get home but most of the time I'm on Ubuntu anyway.

**Comment by sornas** [comment]
Same error on Ubuntu but fixed with instructions from https://github.com/ggez/ggez/issues/100.

`sudo apt install libasound2-dev`
